### ISSUE TITLE
Override defaultTXTRecordPrefix in ExternalDNS

### ISSUE THREAD

**Issue by Aldjinn** [openshift/external-dns-operator#164]
Hi,
is it possible to override defaultTXTRecordPrefix in the yaml file?

My current yaml is looking this way:
```yaml
apiVersion: externaldns.olm.openshift.io/v1alpha1
kind: ExternalDNS
metadata:
  name: my-internal-domain
  namespace: external-dns
spec:
  provider:
    type: AWS
    aws:
      credentials:
        name: aws-access-key
  source:
    openshiftRouteOptions:
      routerName: default
    type: OpenShiftRoute
  zones:
    - MY_ZONE_ID
```

After having a quick look into the sourcecode, I've found
```
defaultTXTRecordPrefix   = "external-dns-"
```
but no possibility to provide this value via the ExternalDNSProvider struct.

Any ideas?

Thx.
