### ISSUE TITLE
Support Nodename for ExternalDNSServiceSourceOptions

### ISSUE THREAD

**Issue by git001** [openshift/external-dns-operator#189]
We need to add the machine names into a corporate DNS therefore would it be very helpfull to be able to use the node status for external DNS or some labels or annotations.

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    k8s.ovn.org/host-addresses: '["10.x.x.x"]'
    # other annotations
  labels:
    kubernetes.io/hostname: mycluster-p8zqf-worker-chpgv
    # other labels
  name: mycluster-p8zqf-worker-chpgv
.......
status:
  addresses:
  - address: 10.x.x.x
    type: ExternalIP
  - address: 10.x.x.x
    type: InternalIP
  - address: mycluster-p8zqf-worker-chpgv
    type: Hostname
.......
```

Maybe this is already possible with `hostnameAnnotation`  [HostnameAnnotationPolicy](https://github.com/openshift/external-dns-operator/blob/main/api/v1beta1/externaldns_types.go#L395) but it looks to me that this annotation is only possible for the supported `serviceType`s https://github.com/openshift/external-dns-operator/blob/fd1d055f84381bd12b431c071a3255c935fdbfe3/api/v1beta1/externaldns_types.go#L471
