### ISSUE TITLE
Support for IRSA for AWS Provider

### ISSUE THREAD

**Issue by scottd018** [openshift/external-dns-operator#190]
As per https://github.com/openshift/external-dns-operator/blob/main/api/v1beta1/externaldns_types.go#L260 IRSA is not currently supported.  This should allow a consumer of the external-dns to pass in a Role ARN and have the service account annotated as follows for an AWS provider:

```yaml
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT>:role/<ROLE>"
```
